/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(cfar2D.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(bbcdef427c4a7f994087537034d7d484)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/plasma/cfar2D.h>
// pydoc.h is automatically generated in the build directory
#include <cfar2D_pydoc.h>

void bind_cfar2D(py::module& m)
{

    using cfar2D = ::gr::plasma::cfar2D;


    py::class_<cfar2D, gr::block, gr::basic_block, std::shared_ptr<cfar2D>>(
        m, "cfar2D", D(cfar2D))

        .def(py::init(&cfar2D::make),
             py::arg("guard_win_size"),
             py::arg("train_win_size"),
             py::arg("pfa"),
             py::arg("num_pulse_cpi"),
             D(cfar2D, make))


        .def("set_msg_queue_depth",
             &cfar2D::set_msg_queue_depth,
             py::arg("arg0"),
             D(cfar2D, set_msg_queue_depth))


        .def("set_backend", &cfar2D::set_backend, py::arg("arg0"), D(cfar2D, set_backend))

        ;
}
