/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(pdu_file_sink.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(3d6210dd45506814856c1457ef7838cf)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/plasma/pdu_file_sink.h>
// pydoc.h is automatically generated in the build directory
#include <pdu_file_sink_pydoc.h>

void bind_pdu_file_sink(py::module& m)
{

    using pdu_file_sink    = ::gr::plasma::pdu_file_sink;


    py::class_<pdu_file_sink, gr::block, gr::basic_block,
        std::shared_ptr<pdu_file_sink>>(m, "pdu_file_sink", D(pdu_file_sink))

        .def(py::init(&pdu_file_sink::make),
           py::arg("data_filename"),
           py::arg("meta_filename"),
           D(pdu_file_sink,make)
        )
        



        ;




}








