/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(pdu_slicer.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(a82e77966b40025b0ccbe639985b54df)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/plasma/pdu_slicer.h>
// pydoc.h is automatically generated in the build directory
#include <pdu_slicer_pydoc.h>

void bind_pdu_slicer(py::module& m)
{

    using pdu_slicer    = gr::plasma::pdu_slicer;


    py::class_<pdu_slicer, gr::block, gr::basic_block,
        std::shared_ptr<pdu_slicer>>(m, "pdu_slicer", D(pdu_slicer))

        .def(py::init(&pdu_slicer::make),
           D(pdu_slicer,make)
        )
        



        ;




}








