/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(simulate_rx.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(b8b4f568c8cecda531cf99a49e0c9333)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/plasma/simulate_rx.h>
// pydoc.h is automatically generated in the build directory
#include <simulate_rx_pydoc.h>

void bind_simulate_rx(py::module& m)
{

    using simulate_rx = ::gr::plasma::simulate_rx;


    py::class_<simulate_rx, gr::block, gr::basic_block, std::shared_ptr<simulate_rx>>(
        m, "simulate_rx", D(simulate_rx))

        .def(py::init(&simulate_rx::make),
             py::arg("delay"),
             py::arg("scale"),
             D(simulate_rx, make))


        ;
}
