/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(waveform_controller.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(338d303e75b69f584a70ed095c35332d)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/plasma/waveform_controller.h>
// pydoc.h is automatically generated in the build directory
#include <waveform_controller_pydoc.h>

void bind_waveform_controller(py::module& m)
{

    using waveform_controller = ::gr::plasma::waveform_controller;


    py::class_<waveform_controller,
               gr::block,
               gr::basic_block,
               std::shared_ptr<waveform_controller>>(
        m, "waveform_controller", D(waveform_controller))

        .def(py::init(&waveform_controller::make),
             py::arg("prf"),
             py::arg("samp_rate"),
             D(waveform_controller, make))


        .def("init_meta_dict",
             &waveform_controller::init_meta_dict,
             py::arg("prf_key"),
             py::arg("samp_rate_key"),
             D(waveform_controller, init_meta_dict))

        ;
}
